version: '3'
services:
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=example
    - MONGO_INITDB_DATABASE=example
  
  mongo-express:
    image: mongo-express
    ports:
      - 8888:8081
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongodb
    - ME_CONFIG_MONGODB_PORT=27017
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    - ME_CONFIG_MONGODB_AUTH_USERNAME=root
    - ME_CONFIG_MONGODB_AUTH_PASSWORD=example
    - ME_CONFIG_BASICAUTH_USERNAME=root
    - ME_CONFIG_BASICAUTH_PASSWORD=example
    depends_on:
      - mongodb


